-- ============================================================
-- DICOR · Módulo de STOCK / Inventario
-- Ejecutar UNA VEZ en: Supabase Dashboard → SQL Editor → New query.
-- Es seguro: NO borra datos. Solo agrega columnas, una tabla nueva
-- y actualiza las funciones. Se puede volver a ejecutar sin problemas.
-- ============================================================

-- ---------- 1. Columnas de stock en productos ----------
-- stock: cantidad actual en depósito. stock_minimo: umbral de alerta.
alter table productos add column if not exists stock integer not null default 0;
alter table productos add column if not exists stock_minimo integer not null default 0;

-- ---------- 2. Tabla de movimientos (auditoría) ----------
-- Cada entrada, salida o ajuste queda registrado, igual que el
-- historial de precios. Permite reconstruir cómo se llegó al stock actual.
create table if not exists movimientos_stock (
    id bigint generated by default as identity primary key,
    producto_id bigint references productos(id) on delete set null,
    producto_codigo text,
    producto_descripcion text,
    tipo text not null,            -- 'ingreso' | 'egreso' | 'ajuste'
    cantidad integer not null,     -- magnitud del movimiento (siempre positiva)
    stock_anterior integer not null,
    stock_nuevo integer not null,
    motivo text,
    remito_id bigint references remitos(id) on delete set null,
    fecha timestamptz default now()
);

create index if not exists idx_movimientos_producto on movimientos_stock (producto_id);
create index if not exists idx_movimientos_fecha on movimientos_stock (fecha desc);

-- ---------- 3. Seguridad (RLS) ----------
alter table movimientos_stock enable row level security;
drop policy if exists "acceso total autenticado" on movimientos_stock;
create policy "acceso total autenticado" on movimientos_stock
    for all to authenticated using (true) with check (true);

-- ---------- 4. Registrar un movimiento manual ----------
-- Actualiza el stock del producto y deja el registro, todo en una operación.
--   tipo 'ingreso' → suma  p_cantidad
--   tipo 'egreso'  → resta p_cantidad
--   tipo 'ajuste'  → fija el stock exactamente en p_cantidad
-- Devuelve el stock resultante.
create or replace function registrar_movimiento_stock(
    p_producto_id bigint,
    p_tipo text,
    p_cantidad integer,
    p_motivo text
)
returns integer
language plpgsql
as $$
declare
    v_codigo text;
    v_desc text;
    v_anterior integer;
    v_nuevo integer;
    v_magnitud integer;
begin
    if p_tipo in ('ingreso', 'egreso') and p_cantidad < 0 then
        raise exception 'La cantidad no puede ser negativa';
    end if;

    if p_tipo = 'ingreso' then
        -- UPDATE relativo y atómico: evita "lost update" entre movimientos concurrentes
        v_magnitud := abs(p_cantidad);
        update productos set stock = stock + v_magnitud, fecha_actualizacion = now()
        where id = p_producto_id
        returning codigo, descripcion, stock - v_magnitud, stock
        into v_codigo, v_desc, v_anterior, v_nuevo;
    elsif p_tipo = 'egreso' then
        v_magnitud := abs(p_cantidad);
        update productos set stock = stock - v_magnitud, fecha_actualizacion = now()
        where id = p_producto_id
        returning codigo, descripcion, stock + v_magnitud, stock
        into v_codigo, v_desc, v_anterior, v_nuevo;
    elsif p_tipo = 'ajuste' then
        -- Ajuste fija un valor absoluto: se toma lock de la fila (for update)
        -- para leer el stock previo de forma consistente antes de sobreescribir.
        select stock, codigo, descripcion into v_anterior, v_codigo, v_desc
        from productos where id = p_producto_id for update;
        if not found then
            raise exception 'Producto % no encontrado', p_producto_id;
        end if;
        v_nuevo := p_cantidad;
        v_magnitud := abs(p_cantidad - coalesce(v_anterior, 0));
        update productos set stock = v_nuevo, fecha_actualizacion = now()
        where id = p_producto_id;
    else
        raise exception 'Tipo de movimiento inválido: %', p_tipo;
    end if;

    if not found then
        raise exception 'Producto % no encontrado', p_producto_id;
    end if;

    insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                   tipo, cantidad, stock_anterior, stock_nuevo, motivo)
    values (p_producto_id, v_codigo, v_desc,
            p_tipo, v_magnitud, coalesce(v_anterior, 0), v_nuevo, coalesce(p_motivo, ''));

    return v_nuevo;
end;
$$;

-- ---------- 5. crear_remito ahora descuenta stock ----------
-- Mantiene exactamente lo de antes (crea remito + items en una transacción)
-- y además, por cada ítem cuyo código exista en el catálogo, descuenta la
-- cantidad del stock y registra el movimiento ligado al remito.
create or replace function crear_remito(p_remito jsonb, p_items jsonb)
returns bigint
language plpgsql
as $$
declare
    v_id bigint;
    v_numero text;
    i jsonb;
    v_cant integer;
    v_prod_id bigint;
    v_prod_codigo text;
    v_prod_desc text;
    v_anterior integer;
    v_nuevo integer;
begin
    v_numero := p_remito->>'numero';

    insert into remitos (numero, fecha, cliente_nombre, cliente_domicilio, cliente_cuit,
                         condicion_iva, condicion_venta, total, ruta_pdf)
    values (
        p_remito->>'numero',
        (p_remito->>'fecha')::date,
        p_remito->>'cliente_nombre',
        p_remito->>'cliente_domicilio',
        p_remito->>'cliente_cuit',
        coalesce(p_remito->>'condicion_iva', 'Consumidor Final'),
        coalesce(p_remito->>'condicion_venta', 'Contado'),
        (p_remito->>'total')::double precision,
        p_remito->>'ruta_pdf'
    )
    returning id into v_id;

    insert into remito_items (remito_id, codigo, cantidad, descripcion, precio_unitario, bonificacion, subtotal)
    select
        v_id,
        elem->>'codigo',
        (elem->>'cantidad')::integer,
        elem->>'descripcion',
        (elem->>'precio_unitario')::double precision,
        coalesce((elem->>'bonificacion')::double precision, 0),
        (elem->>'subtotal')::double precision
    from jsonb_array_elements(p_items) as elem;

    -- Descuento de stock por cada ítem con código existente.
    -- El UPDATE es relativo (stock = stock - v_cant) y atómico: evita el
    -- "lost update" si se generan dos remitos del mismo producto a la vez.
    -- Se permite stock negativo a propósito: refleja una venta real aunque
    -- el stock cargado no alcance (queda en rojo como aviso de reposición).
    for i in select * from jsonb_array_elements(p_items)
    loop
        v_cant := coalesce((i->>'cantidad')::integer, 0);
        if v_cant > 0 and coalesce(i->>'codigo', '') <> '' then
            update productos
            set stock = stock - v_cant
            where codigo = (i->>'codigo')
            returning id, codigo, descripcion, stock + v_cant, stock
            into v_prod_id, v_prod_codigo, v_prod_desc, v_anterior, v_nuevo;
            if found then
                insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                               tipo, cantidad, stock_anterior, stock_nuevo, motivo, remito_id)
                values (v_prod_id, v_prod_codigo, v_prod_desc,
                        'egreso', v_cant, v_anterior, v_nuevo,
                        'Venta · remito ' || v_numero, v_id);
            end if;
        end if;
    end loop;

    return v_id;
end;
$$;
