-- ============================================================
-- DICOR - Esquema de base de datos para Supabase (Postgres)
-- Mismo formato de tablas que la app de escritorio (dicor.db),
-- incluida la tabla historial_precios que en el escritorio
-- nunca se creaba (causa del bug del historial).
--
-- Ejecutar UNA VEZ en: Supabase Dashboard → SQL Editor → New query
-- Después ejecutar seed.sql para cargar los datos.
-- ============================================================

-- ---------- Tablas ----------

create table if not exists clientes (
    id bigint generated by default as identity primary key,
    nombre text not null,
    domicilio text,
    cuit text,
    condicion_iva text,
    condicion_venta text,
    fecha_creacion timestamptz default now()
);

create table if not exists productos (
    id bigint generated by default as identity primary key,
    codigo text unique,
    descripcion text not null,
    precio_unitario double precision not null,
    categoria text default 'CARBONES',
    -- Control de stock: cantidad en depósito y umbral de alerta de reposición.
    stock integer not null default 0,
    stock_minimo integer not null default 0,
    fecha_actualizacion timestamptz default now()
);

create table if not exists remitos (
    id bigint generated by default as identity primary key,
    numero text unique not null,
    fecha date not null,
    cliente_id bigint references clientes(id),
    cliente_nombre text,
    cliente_domicilio text,
    cliente_cuit text,
    -- Nuevas columnas (con default) para poder regenerar el PDF de
    -- remitos viejos desde la web. No alteran los datos existentes.
    condicion_iva text default 'Consumidor Final',
    condicion_venta text default 'Contado',
    total double precision not null,
    estado text default 'Completado',
    ruta_pdf text,
    fecha_creacion timestamptz default now()
);

create table if not exists remito_items (
    id bigint generated by default as identity primary key,
    remito_id bigint not null references remitos(id) on delete cascade,
    codigo text,
    cantidad integer not null,
    descripcion text not null,
    precio_unitario double precision not null,
    bonificacion double precision default 0,
    subtotal double precision not null
);

create table if not exists historial_precios (
    id bigint generated by default as identity primary key,
    producto_codigo text not null,
    producto_descripcion text,
    precio_anterior double precision not null,
    precio_nuevo double precision not null,
    porcentaje_cambio double precision,
    categoria text,
    fecha_cambio timestamptz default now()
);

-- Movimientos de stock (entradas, salidas y ajustes) para auditoría.
create table if not exists movimientos_stock (
    id bigint generated by default as identity primary key,
    producto_id bigint references productos(id) on delete set null,
    producto_codigo text,
    producto_descripcion text,
    tipo text not null,            -- 'ingreso' | 'egreso' | 'ajuste'
    cantidad integer not null,     -- magnitud del movimiento (siempre positiva)
    stock_anterior integer not null,
    stock_nuevo integer not null,
    motivo text,
    remito_id bigint references remitos(id) on delete set null,
    fecha timestamptz default now()
);

create index if not exists idx_remito_items_remito on remito_items (remito_id);
create index if not exists idx_remitos_fecha on remitos (fecha);
create index if not exists idx_historial_fecha on historial_precios (fecha_cambio desc);
create index if not exists idx_historial_codigo on historial_precios (producto_codigo);
create index if not exists idx_movimientos_producto on movimientos_stock (producto_id);
create index if not exists idx_movimientos_fecha on movimientos_stock (fecha desc);

-- ---------- Seguridad (Row Level Security) ----------
-- Solo usuarios autenticados (vos, con tu usuario creado en
-- Authentication → Users) pueden leer/escribir. El público no ve nada.

alter table clientes          enable row level security;
alter table productos         enable row level security;
alter table remitos           enable row level security;
alter table remito_items      enable row level security;
alter table historial_precios enable row level security;
alter table movimientos_stock enable row level security;

drop policy if exists "acceso total autenticado" on clientes;
create policy "acceso total autenticado" on clientes
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on productos;
create policy "acceso total autenticado" on productos
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on remitos;
create policy "acceso total autenticado" on remitos
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on remito_items;
create policy "acceso total autenticado" on remito_items
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on historial_precios;
create policy "acceso total autenticado" on historial_precios
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on movimientos_stock;
create policy "acceso total autenticado" on movimientos_stock
    for all to authenticated using (true) with check (true);

-- ---------- Funciones ----------

-- Crea el remito y sus items en una sola transacción (todo o nada) y
-- descuenta el stock de cada ítem cuyo código exista en el catálogo,
-- dejando registrado el movimiento.
create or replace function crear_remito(p_remito jsonb, p_items jsonb)
returns bigint
language plpgsql
as $$
declare
    v_id bigint;
    v_numero text;
    i jsonb;
    v_cant integer;
    v_prod_id bigint;
    v_prod_codigo text;
    v_prod_desc text;
    v_anterior integer;
    v_nuevo integer;
begin
    v_numero := p_remito->>'numero';

    insert into remitos (numero, fecha, cliente_nombre, cliente_domicilio, cliente_cuit,
                         condicion_iva, condicion_venta, total, ruta_pdf)
    values (
        p_remito->>'numero',
        (p_remito->>'fecha')::date,
        p_remito->>'cliente_nombre',
        p_remito->>'cliente_domicilio',
        p_remito->>'cliente_cuit',
        coalesce(p_remito->>'condicion_iva', 'Consumidor Final'),
        coalesce(p_remito->>'condicion_venta', 'Contado'),
        (p_remito->>'total')::double precision,
        p_remito->>'ruta_pdf'
    )
    returning id into v_id;

    insert into remito_items (remito_id, codigo, cantidad, descripcion, precio_unitario, bonificacion, subtotal)
    select
        v_id,
        i->>'codigo',
        (i->>'cantidad')::integer,
        i->>'descripcion',
        (i->>'precio_unitario')::double precision,
        coalesce((i->>'bonificacion')::double precision, 0),
        (i->>'subtotal')::double precision
    from jsonb_array_elements(p_items) as i;

    -- Descuento de stock por cada ítem con código existente.
    -- El UPDATE es relativo (stock = stock - v_cant) y atómico: evita el
    -- "lost update" si se generan dos remitos del mismo producto a la vez.
    -- Se permite stock negativo a propósito: refleja una venta real aunque
    -- el stock cargado no alcance (queda en rojo como aviso de reposición).
    for i in select * from jsonb_array_elements(p_items)
    loop
        v_cant := coalesce((i->>'cantidad')::integer, 0);
        if v_cant > 0 and coalesce(i->>'codigo', '') <> '' then
            update productos
            set stock = stock - v_cant
            where codigo = (i->>'codigo')
            returning id, codigo, descripcion, stock + v_cant, stock
            into v_prod_id, v_prod_codigo, v_prod_desc, v_anterior, v_nuevo;
            if found then
                insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                               tipo, cantidad, stock_anterior, stock_nuevo, motivo, remito_id)
                values (v_prod_id, v_prod_codigo, v_prod_desc,
                        'egreso', v_cant, v_anterior, v_nuevo,
                        'Venta · remito ' || v_numero, v_id);
            end if;
        end if;
    end loop;

    return v_id;
end;
$$;

-- Registra un movimiento de stock manual (ingreso/egreso/ajuste),
-- actualizando el producto y dejando el registro de auditoría.
create or replace function registrar_movimiento_stock(
    p_producto_id bigint,
    p_tipo text,
    p_cantidad integer,
    p_motivo text
)
returns integer
language plpgsql
as $$
declare
    v_codigo text;
    v_desc text;
    v_anterior integer;
    v_nuevo integer;
    v_magnitud integer;
begin
    if p_tipo in ('ingreso', 'egreso') and p_cantidad < 0 then
        raise exception 'La cantidad no puede ser negativa';
    end if;

    if p_tipo = 'ingreso' then
        -- UPDATE relativo y atómico: evita "lost update" entre movimientos concurrentes
        v_magnitud := abs(p_cantidad);
        update productos set stock = stock + v_magnitud, fecha_actualizacion = now()
        where id = p_producto_id
        returning codigo, descripcion, stock - v_magnitud, stock
        into v_codigo, v_desc, v_anterior, v_nuevo;
    elsif p_tipo = 'egreso' then
        v_magnitud := abs(p_cantidad);
        update productos set stock = stock - v_magnitud, fecha_actualizacion = now()
        where id = p_producto_id
        returning codigo, descripcion, stock + v_magnitud, stock
        into v_codigo, v_desc, v_anterior, v_nuevo;
    elsif p_tipo = 'ajuste' then
        -- Ajuste fija un valor absoluto: se toma lock de la fila (for update)
        -- para leer el stock previo de forma consistente antes de sobreescribir.
        select stock, codigo, descripcion into v_anterior, v_codigo, v_desc
        from productos where id = p_producto_id for update;
        if not found then
            raise exception 'Producto % no encontrado', p_producto_id;
        end if;
        v_nuevo := p_cantidad;
        v_magnitud := abs(p_cantidad - coalesce(v_anterior, 0));
        update productos set stock = v_nuevo, fecha_actualizacion = now()
        where id = p_producto_id;
    else
        raise exception 'Tipo de movimiento inválido: %', p_tipo;
    end if;

    if not found then
        raise exception 'Producto % no encontrado', p_producto_id;
    end if;

    insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                   tipo, cantidad, stock_anterior, stock_nuevo, motivo)
    values (p_producto_id, v_codigo, v_desc,
            p_tipo, v_magnitud, coalesce(v_anterior, 0), v_nuevo, coalesce(p_motivo, ''));

    return v_nuevo;
end;
$$;

-- Aplica un aumento (o baja, con porcentaje negativo) a una categoría
-- o a todos los productos, registrando cada cambio en historial_precios.
create or replace function aplicar_aumento_precios(p_categoria text, p_porcentaje double precision)
returns integer
language plpgsql
as $$
declare
    v_count integer;
begin
    insert into historial_precios (producto_codigo, producto_descripcion, precio_anterior,
                                   precio_nuevo, porcentaje_cambio, categoria)
    select codigo, descripcion, precio_unitario,
           precio_unitario * (1 + p_porcentaje / 100.0), p_porcentaje, categoria
    from productos
    where p_categoria is null or p_categoria in ('TODAS', 'TODOS') or categoria = p_categoria;

    update productos
    set precio_unitario = precio_unitario * (1 + p_porcentaje / 100.0),
        fecha_actualizacion = now()
    where p_categoria is null or p_categoria in ('TODAS', 'TODOS') or categoria = p_categoria;

    get diagnostics v_count = row_count;
    return v_count;
end;
$$;
