-- ============================================================
-- DICOR - Esquema de base de datos para Supabase (Postgres)
-- Mismo formato de tablas que la app de escritorio (dicor.db),
-- incluida la tabla historial_precios que en el escritorio
-- nunca se creaba (causa del bug del historial).
--
-- Ejecutar UNA VEZ en: Supabase Dashboard → SQL Editor → New query
-- Después ejecutar seed.sql para cargar los datos.
-- ============================================================

-- ---------- Tablas ----------

create table if not exists clientes (
    id bigint generated by default as identity primary key,
    nombre text not null,
    domicilio text,
    cuit text,
    condicion_iva text,
    condicion_venta text,
    fecha_creacion timestamptz default now()
);

create table if not exists productos (
    id bigint generated by default as identity primary key,
    codigo text unique,
    descripcion text not null,
    precio_unitario double precision not null,
    categoria text default 'CARBONES',
    fecha_actualizacion timestamptz default now()
);

create table if not exists remitos (
    id bigint generated by default as identity primary key,
    numero text unique not null,
    fecha date not null,
    cliente_id bigint references clientes(id),
    cliente_nombre text,
    cliente_domicilio text,
    cliente_cuit text,
    -- Nuevas columnas (con default) para poder regenerar el PDF de
    -- remitos viejos desde la web. No alteran los datos existentes.
    condicion_iva text default 'Consumidor Final',
    condicion_venta text default 'Contado',
    total double precision not null,
    estado text default 'Completado',
    ruta_pdf text,
    fecha_creacion timestamptz default now()
);

create table if not exists remito_items (
    id bigint generated by default as identity primary key,
    remito_id bigint not null references remitos(id) on delete cascade,
    codigo text,
    cantidad integer not null,
    descripcion text not null,
    precio_unitario double precision not null,
    bonificacion double precision default 0,
    subtotal double precision not null
);

create table if not exists historial_precios (
    id bigint generated by default as identity primary key,
    producto_codigo text not null,
    producto_descripcion text,
    precio_anterior double precision not null,
    precio_nuevo double precision not null,
    porcentaje_cambio double precision,
    categoria text,
    fecha_cambio timestamptz default now()
);

create index if not exists idx_remito_items_remito on remito_items (remito_id);
create index if not exists idx_remitos_fecha on remitos (fecha);
create index if not exists idx_historial_fecha on historial_precios (fecha_cambio desc);
create index if not exists idx_historial_codigo on historial_precios (producto_codigo);

-- ---------- Seguridad (Row Level Security) ----------
-- Solo usuarios autenticados (vos, con tu usuario creado en
-- Authentication → Users) pueden leer/escribir. El público no ve nada.

alter table clientes          enable row level security;
alter table productos         enable row level security;
alter table remitos           enable row level security;
alter table remito_items      enable row level security;
alter table historial_precios enable row level security;

drop policy if exists "acceso total autenticado" on clientes;
create policy "acceso total autenticado" on clientes
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on productos;
create policy "acceso total autenticado" on productos
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on remitos;
create policy "acceso total autenticado" on remitos
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on remito_items;
create policy "acceso total autenticado" on remito_items
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on historial_precios;
create policy "acceso total autenticado" on historial_precios
    for all to authenticated using (true) with check (true);

-- ---------- Funciones ----------

-- Crea el remito y sus items en una sola transacción (todo o nada).
create or replace function crear_remito(p_remito jsonb, p_items jsonb)
returns bigint
language plpgsql
as $$
declare
    v_id bigint;
begin
    insert into remitos (numero, fecha, cliente_nombre, cliente_domicilio, cliente_cuit,
                         condicion_iva, condicion_venta, total, ruta_pdf)
    values (
        p_remito->>'numero',
        (p_remito->>'fecha')::date,
        p_remito->>'cliente_nombre',
        p_remito->>'cliente_domicilio',
        p_remito->>'cliente_cuit',
        coalesce(p_remito->>'condicion_iva', 'Consumidor Final'),
        coalesce(p_remito->>'condicion_venta', 'Contado'),
        (p_remito->>'total')::double precision,
        p_remito->>'ruta_pdf'
    )
    returning id into v_id;

    insert into remito_items (remito_id, codigo, cantidad, descripcion, precio_unitario, bonificacion, subtotal)
    select
        v_id,
        i->>'codigo',
        (i->>'cantidad')::integer,
        i->>'descripcion',
        (i->>'precio_unitario')::double precision,
        coalesce((i->>'bonificacion')::double precision, 0),
        (i->>'subtotal')::double precision
    from jsonb_array_elements(p_items) as i;

    return v_id;
end;
$$;

-- Aplica un aumento (o baja, con porcentaje negativo) a una categoría
-- o a todos los productos, registrando cada cambio en historial_precios.
create or replace function aplicar_aumento_precios(p_categoria text, p_porcentaje double precision)
returns integer
language plpgsql
as $$
declare
    v_count integer;
begin
    insert into historial_precios (producto_codigo, producto_descripcion, precio_anterior,
                                   precio_nuevo, porcentaje_cambio, categoria)
    select codigo, descripcion, precio_unitario,
           precio_unitario * (1 + p_porcentaje / 100.0), p_porcentaje, categoria
    from productos
    where p_categoria is null or p_categoria in ('TODAS', 'TODOS') or categoria = p_categoria;

    update productos
    set precio_unitario = precio_unitario * (1 + p_porcentaje / 100.0),
        fecha_actualizacion = now()
    where p_categoria is null or p_categoria in ('TODAS', 'TODOS') or categoria = p_categoria;

    get diagnostics v_count = row_count;
    return v_count;
end;
$$;
