-- ============================================================
-- DICOR - Esquema COMPLETO de la base de datos (Supabase/Postgres)
--
-- Es el único archivo SQL del proyecto: refleja el estado actual de
-- la base (tablas, seguridad RLS y todas las funciones). Sirve para
-- recrear la base desde cero en un proyecto de Supabase nuevo.
-- Solo estructura: los datos se restauran desde un backup JSON
-- (botón "Backup" en el Panel de la web).
--
-- Ejecutar UNA VEZ en: Supabase Dashboard → SQL Editor → New query.
-- No borra datos: es seguro re-ejecutarlo para actualizar funciones.
-- ============================================================

-- ---------- Tablas ----------

create table if not exists clientes (
    id bigint generated by default as identity primary key,
    nombre text not null,
    domicilio text,
    cuit text,
    condicion_iva text,
    condicion_venta text,
    fecha_creacion timestamptz default now()
);

create table if not exists productos (
    id bigint generated by default as identity primary key,
    codigo text unique,
    descripcion text not null,
    precio_unitario numeric(12,2) not null,
    categoria text default 'CARBONES',
    -- Control de stock: cantidad en depósito y umbral de alerta de reposición.
    stock integer not null default 0,
    stock_minimo integer not null default 0,
    fecha_actualizacion timestamptz default now()
);

create table if not exists remitos (
    id bigint generated by default as identity primary key,
    numero text unique not null,
    fecha date not null,
    cliente_id bigint references clientes(id),
    cliente_nombre text,
    cliente_domicilio text,
    cliente_cuit text,
    -- Nuevas columnas (con default) para poder regenerar el PDF de
    -- remitos viejos desde la web. No alteran los datos existentes.
    condicion_iva text default 'Consumidor Final',
    condicion_venta text default 'Contado',
    total numeric(12,2) not null,
    estado text default 'Completado',
    ruta_pdf text,
    fecha_creacion timestamptz default now()
);

create table if not exists remito_items (
    id bigint generated by default as identity primary key,
    remito_id bigint not null references remitos(id) on delete cascade,
    codigo text,
    cantidad integer not null,
    descripcion text not null,
    precio_unitario numeric(12,2) not null,
    bonificacion numeric(5,2) default 0,
    subtotal numeric(12,2) not null
);

create table if not exists historial_precios (
    id bigint generated by default as identity primary key,
    producto_codigo text not null,
    producto_descripcion text,
    precio_anterior numeric(12,2) not null,
    precio_nuevo numeric(12,2) not null,
    porcentaje_cambio numeric(8,2),
    categoria text,
    fecha_cambio timestamptz default now()
);

-- Movimientos de stock (entradas, salidas y ajustes) para auditoría.
create table if not exists movimientos_stock (
    id bigint generated by default as identity primary key,
    producto_id bigint references productos(id) on delete set null,
    producto_codigo text,
    producto_descripcion text,
    tipo text not null,            -- 'ingreso' | 'egreso' | 'ajuste'
    cantidad integer not null,     -- magnitud del movimiento (siempre positiva)
    stock_anterior integer not null,
    stock_nuevo integer not null,
    motivo text,
    remito_id bigint references remitos(id) on delete set null,
    fecha timestamptz default now()
);

create index if not exists idx_remito_items_remito on remito_items (remito_id);
create index if not exists idx_remitos_fecha on remitos (fecha);
create index if not exists idx_historial_fecha on historial_precios (fecha_cambio desc);
create index if not exists idx_historial_codigo on historial_precios (producto_codigo);
create index if not exists idx_movimientos_producto on movimientos_stock (producto_id);
create index if not exists idx_movimientos_fecha on movimientos_stock (fecha desc);

-- ---------- Seguridad (Row Level Security) ----------
-- Solo usuarios autenticados (vos, con tu usuario creado en
-- Authentication → Users) pueden leer/escribir. El público no ve nada.

alter table clientes          enable row level security;
alter table productos         enable row level security;
alter table remitos           enable row level security;
alter table remito_items      enable row level security;
alter table historial_precios enable row level security;
alter table movimientos_stock enable row level security;

drop policy if exists "acceso total autenticado" on clientes;
create policy "acceso total autenticado" on clientes
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on productos;
create policy "acceso total autenticado" on productos
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on remitos;
create policy "acceso total autenticado" on remitos
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on remito_items;
create policy "acceso total autenticado" on remito_items
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on historial_precios;
create policy "acceso total autenticado" on historial_precios
    for all to authenticated using (true) with check (true);

drop policy if exists "acceso total autenticado" on movimientos_stock;
create policy "acceso total autenticado" on movimientos_stock
    for all to authenticated using (true) with check (true);

-- ---------- Funciones ----------

-- Calcula el próximo número de remito ('0001-NNN') a partir del mayor
-- sufijo existente. La web lo usa para mostrarlo; la asignación definitiva
-- la hace crear_remito bajo advisory lock.
create or replace function proximo_numero_remito()
returns text
language sql
stable
as $$
    select '0001-' || lpad(
        (coalesce(max((split_part(numero, '-', 2))::integer), 0) + 1)::text, 3, '0')
    from remitos
    where split_part(numero, '-', 2) ~ '^[0-9]+$';
$$;

-- Crea el remito y sus items en una sola transacción (todo o nada) y
-- descuenta el stock de cada ítem cuyo código exista en el catálogo,
-- dejando registrado el movimiento. El número se asigna en el servidor
-- (serializado con advisory lock) y se devuelve en el jsonb {id, numero}.
drop function if exists crear_remito(jsonb, jsonb);

create or replace function crear_remito(p_remito jsonb, p_items jsonb)
returns jsonb
language plpgsql
as $$
declare
    v_id bigint;
    v_numero text;
    v_codigos_invalidos text;
    i jsonb;
    v_cant integer;
    v_prod_id bigint;
    v_prod_codigo text;
    v_prod_desc text;
    v_anterior integer;
    v_nuevo integer;
begin
    -- Valida que todos los códigos cargados existan en el catálogo:
    -- un código inexistente no descontaría stock y ensucia los reportes.
    -- Los ítems sin código siguen permitidos (descripción manual).
    select string_agg(distinct elem->>'codigo', ', ')
    into v_codigos_invalidos
    from jsonb_array_elements(p_items) as elem
    where coalesce(elem->>'codigo', '') <> ''
      and not exists (select 1 from productos p where p.codigo = elem->>'codigo');
    if v_codigos_invalidos is not null then
        raise exception 'Estos códigos no existen en el catálogo: %. Corregilos o dejá el código vacío.', v_codigos_invalidos;
    end if;

    -- Serializa la asignación del número entre transacciones concurrentes
    perform pg_advisory_xact_lock(hashtext('remitos_numero'));
    v_numero := proximo_numero_remito();

    insert into remitos (numero, fecha, cliente_id, cliente_nombre, cliente_domicilio, cliente_cuit,
                         condicion_iva, condicion_venta, total, ruta_pdf)
    values (
        v_numero,
        (p_remito->>'fecha')::date,
        nullif(p_remito->>'cliente_id', '')::bigint,
        p_remito->>'cliente_nombre',
        p_remito->>'cliente_domicilio',
        p_remito->>'cliente_cuit',
        coalesce(p_remito->>'condicion_iva', 'Consumidor Final'),
        coalesce(p_remito->>'condicion_venta', 'Contado'),
        round((p_remito->>'total')::numeric, 2),
        'remito_' || regexp_replace(coalesce(p_remito->>'cliente_nombre', ''), '[^a-zA-Z0-9]', '_', 'g')
            || '_' || v_numero || '.pdf'
    )
    returning id into v_id;

    insert into remito_items (remito_id, codigo, cantidad, descripcion, precio_unitario, bonificacion, subtotal)
    select
        v_id,
        elem->>'codigo',
        (elem->>'cantidad')::integer,
        elem->>'descripcion',
        round((elem->>'precio_unitario')::numeric, 2),
        round(coalesce((elem->>'bonificacion')::numeric, 0), 2),
        round((elem->>'subtotal')::numeric, 2)
    from jsonb_array_elements(p_items) as elem;

    -- Descuento de stock por cada ítem con código existente.
    -- El UPDATE es relativo (stock = stock - v_cant) y atómico: evita el
    -- "lost update" si se generan dos remitos del mismo producto a la vez.
    -- Se permite stock negativo a propósito: refleja una venta real aunque
    -- el stock cargado no alcance (queda en rojo como aviso de reposición).
    for i in select * from jsonb_array_elements(p_items)
    loop
        v_cant := coalesce((i->>'cantidad')::integer, 0);
        if v_cant > 0 and coalesce(i->>'codigo', '') <> '' then
            update productos
            set stock = stock - v_cant
            where codigo = (i->>'codigo')
            returning id, codigo, descripcion, stock + v_cant, stock
            into v_prod_id, v_prod_codigo, v_prod_desc, v_anterior, v_nuevo;
            if found then
                insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                               tipo, cantidad, stock_anterior, stock_nuevo, motivo, remito_id)
                values (v_prod_id, v_prod_codigo, v_prod_desc,
                        'egreso', v_cant, v_anterior, v_nuevo,
                        'Venta · remito ' || v_numero, v_id);
            end if;
        end if;
    end loop;

    return jsonb_build_object('id', v_id, 'numero', v_numero);
end;
$$;

-- Elimina un remito reponiendo el stock descontado al crearlo y dejando
-- registrado el movimiento de reposición. Los items se borran en cascada.
-- Si el remito ya estaba anulado, el stock ya fue repuesto al anularlo:
-- borrar no debe volver a sumarlo.
create or replace function eliminar_remito(p_remito_id bigint)
returns void
language plpgsql
as $$
declare
    v_numero text;
    v_estado text;
    it record;
    v_prod_id bigint;
    v_codigo text;
    v_desc text;
    v_anterior integer;
    v_nuevo integer;
begin
    select numero, coalesce(estado, 'Completado')
    into v_numero, v_estado
    from remitos where id = p_remito_id for update;
    if not found then
        raise exception 'Remito % no encontrado', p_remito_id;
    end if;

    if v_estado <> 'Anulado' then
        for it in
            select codigo, sum(cantidad) as cantidad
            from remito_items
            where remito_id = p_remito_id and coalesce(codigo, '') <> '' and cantidad > 0
            group by codigo
        loop
            update productos
            set stock = stock + it.cantidad
            where codigo = it.codigo
            returning id, codigo, descripcion, stock - it.cantidad, stock
            into v_prod_id, v_codigo, v_desc, v_anterior, v_nuevo;
            if found then
                insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                               tipo, cantidad, stock_anterior, stock_nuevo, motivo)
                values (v_prod_id, v_codigo, v_desc,
                        'ingreso', it.cantidad, v_anterior, v_nuevo,
                        'Reposición · remito ' || v_numero || ' eliminado');
            end if;
        end loop;
    end if;

    delete from remitos where id = p_remito_id;
end;
$$;

-- Anula un remito: repone el stock (con auditoría) y marca estado='Anulado'.
-- El remito queda visible en el listado pero excluido de las métricas.
create or replace function anular_remito(p_remito_id bigint)
returns void
language plpgsql
as $$
declare
    v_numero text;
    v_estado text;
    it record;
    v_prod_id bigint;
    v_codigo text;
    v_desc text;
    v_anterior integer;
    v_nuevo integer;
begin
    select numero, coalesce(estado, 'Completado')
    into v_numero, v_estado
    from remitos where id = p_remito_id for update;
    if not found then
        raise exception 'Remito % no encontrado', p_remito_id;
    end if;
    if v_estado = 'Anulado' then
        raise exception 'El remito % ya está anulado', v_numero;
    end if;

    for it in
        select codigo, sum(cantidad) as cantidad
        from remito_items
        where remito_id = p_remito_id and coalesce(codigo, '') <> '' and cantidad > 0
        group by codigo
    loop
        update productos
        set stock = stock + it.cantidad
        where codigo = it.codigo
        returning id, codigo, descripcion, stock - it.cantidad, stock
        into v_prod_id, v_codigo, v_desc, v_anterior, v_nuevo;
        if found then
            insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                           tipo, cantidad, stock_anterior, stock_nuevo, motivo, remito_id)
            values (v_prod_id, v_codigo, v_desc,
                    'ingreso', it.cantidad, v_anterior, v_nuevo,
                    'Anulación · remito ' || v_numero, p_remito_id);
        end if;
    end loop;

    update remitos set estado = 'Anulado' where id = p_remito_id;
end;
$$;

-- Edita un remito: repone el stock de los items originales, reemplaza los
-- items y datos (el número no cambia) y descuenta el stock nuevo.
create or replace function actualizar_remito(p_remito_id bigint, p_remito jsonb, p_items jsonb)
returns jsonb
language plpgsql
as $$
declare
    v_numero text;
    v_estado text;
    v_codigos_invalidos text;
    it record;
    i jsonb;
    v_cant integer;
    v_prod_id bigint;
    v_codigo text;
    v_desc text;
    v_anterior integer;
    v_nuevo integer;
begin
    select numero, coalesce(estado, 'Completado')
    into v_numero, v_estado
    from remitos where id = p_remito_id for update;
    if not found then
        raise exception 'Remito % no encontrado', p_remito_id;
    end if;
    if v_estado = 'Anulado' then
        raise exception 'El remito % está anulado y no se puede editar', v_numero;
    end if;

    -- Misma validación de códigos que en crear_remito, antes de tocar nada
    select string_agg(distinct elem->>'codigo', ', ')
    into v_codigos_invalidos
    from jsonb_array_elements(p_items) as elem
    where coalesce(elem->>'codigo', '') <> ''
      and not exists (select 1 from productos p where p.codigo = elem->>'codigo');
    if v_codigos_invalidos is not null then
        raise exception 'Estos códigos no existen en el catálogo: %. Corregilos o dejá el código vacío.', v_codigos_invalidos;
    end if;

    for it in
        select codigo, sum(cantidad) as cantidad
        from remito_items
        where remito_id = p_remito_id and coalesce(codigo, '') <> '' and cantidad > 0
        group by codigo
    loop
        update productos
        set stock = stock + it.cantidad
        where codigo = it.codigo
        returning id, codigo, descripcion, stock - it.cantidad, stock
        into v_prod_id, v_codigo, v_desc, v_anterior, v_nuevo;
        if found then
            insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                           tipo, cantidad, stock_anterior, stock_nuevo, motivo, remito_id)
            values (v_prod_id, v_codigo, v_desc,
                    'ingreso', it.cantidad, v_anterior, v_nuevo,
                    'Edición · remito ' || v_numero || ' (reversión)', p_remito_id);
        end if;
    end loop;

    delete from remito_items where remito_id = p_remito_id;

    update remitos
    set fecha             = (p_remito->>'fecha')::date,
        cliente_id        = nullif(p_remito->>'cliente_id', '')::bigint,
        cliente_nombre    = p_remito->>'cliente_nombre',
        cliente_domicilio = p_remito->>'cliente_domicilio',
        cliente_cuit      = p_remito->>'cliente_cuit',
        condicion_iva     = coalesce(p_remito->>'condicion_iva', 'Consumidor Final'),
        condicion_venta   = coalesce(p_remito->>'condicion_venta', 'Contado'),
        total             = round((p_remito->>'total')::numeric, 2),
        ruta_pdf          = 'remito_' || regexp_replace(coalesce(p_remito->>'cliente_nombre', ''), '[^a-zA-Z0-9]', '_', 'g')
                                || '_' || v_numero || '.pdf'
    where id = p_remito_id;

    insert into remito_items (remito_id, codigo, cantidad, descripcion, precio_unitario, bonificacion, subtotal)
    select
        p_remito_id,
        elem->>'codigo',
        (elem->>'cantidad')::integer,
        elem->>'descripcion',
        round((elem->>'precio_unitario')::numeric, 2),
        round(coalesce((elem->>'bonificacion')::numeric, 0), 2),
        round((elem->>'subtotal')::numeric, 2)
    from jsonb_array_elements(p_items) as elem;

    for i in select * from jsonb_array_elements(p_items)
    loop
        v_cant := coalesce((i->>'cantidad')::integer, 0);
        if v_cant > 0 and coalesce(i->>'codigo', '') <> '' then
            update productos
            set stock = stock - v_cant
            where codigo = (i->>'codigo')
            returning id, codigo, descripcion, stock + v_cant, stock
            into v_prod_id, v_codigo, v_desc, v_anterior, v_nuevo;
            if found then
                insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                               tipo, cantidad, stock_anterior, stock_nuevo, motivo, remito_id)
                values (v_prod_id, v_codigo, v_desc,
                        'egreso', v_cant, v_anterior, v_nuevo,
                        'Venta · remito ' || v_numero || ' (editado)', p_remito_id);
            end if;
        end if;
    end loop;

    return jsonb_build_object('id', p_remito_id, 'numero', v_numero);
end;
$$;

-- Registra un movimiento de stock manual (ingreso/egreso/ajuste),
-- actualizando el producto y dejando el registro de auditoría.
create or replace function registrar_movimiento_stock(
    p_producto_id bigint,
    p_tipo text,
    p_cantidad integer,
    p_motivo text
)
returns integer
language plpgsql
as $$
declare
    v_codigo text;
    v_desc text;
    v_anterior integer;
    v_nuevo integer;
    v_magnitud integer;
begin
    if p_tipo in ('ingreso', 'egreso') and p_cantidad < 0 then
        raise exception 'La cantidad no puede ser negativa';
    end if;

    if p_tipo = 'ingreso' then
        -- UPDATE relativo y atómico: evita "lost update" entre movimientos concurrentes
        v_magnitud := abs(p_cantidad);
        update productos set stock = stock + v_magnitud, fecha_actualizacion = now()
        where id = p_producto_id
        returning codigo, descripcion, stock - v_magnitud, stock
        into v_codigo, v_desc, v_anterior, v_nuevo;
    elsif p_tipo = 'egreso' then
        v_magnitud := abs(p_cantidad);
        update productos set stock = stock - v_magnitud, fecha_actualizacion = now()
        where id = p_producto_id
        returning codigo, descripcion, stock + v_magnitud, stock
        into v_codigo, v_desc, v_anterior, v_nuevo;
    elsif p_tipo = 'ajuste' then
        -- Ajuste fija un valor absoluto: se toma lock de la fila (for update)
        -- para leer el stock previo de forma consistente antes de sobreescribir.
        select stock, codigo, descripcion into v_anterior, v_codigo, v_desc
        from productos where id = p_producto_id for update;
        if not found then
            raise exception 'Producto % no encontrado', p_producto_id;
        end if;
        v_nuevo := p_cantidad;
        v_magnitud := abs(p_cantidad - coalesce(v_anterior, 0));
        update productos set stock = v_nuevo, fecha_actualizacion = now()
        where id = p_producto_id;
    else
        raise exception 'Tipo de movimiento inválido: %', p_tipo;
    end if;

    if not found then
        raise exception 'Producto % no encontrado', p_producto_id;
    end if;

    insert into movimientos_stock (producto_id, producto_codigo, producto_descripcion,
                                   tipo, cantidad, stock_anterior, stock_nuevo, motivo)
    values (p_producto_id, v_codigo, v_desc,
            p_tipo, v_magnitud, coalesce(v_anterior, 0), v_nuevo, coalesce(p_motivo, ''));

    return v_nuevo;
end;
$$;

-- Aplica un aumento (o baja, con porcentaje negativo) a una categoría
-- o a todos los productos, registrando cada cambio en historial_precios.
create or replace function aplicar_aumento_precios(p_categoria text, p_porcentaje double precision)
returns integer
language plpgsql
as $$
declare
    v_count integer;
begin
    insert into historial_precios (producto_codigo, producto_descripcion, precio_anterior,
                                   precio_nuevo, porcentaje_cambio, categoria)
    select codigo, descripcion, precio_unitario,
           precio_unitario * (1 + p_porcentaje / 100.0), p_porcentaje, categoria
    from productos
    where p_categoria is null or p_categoria in ('TODAS', 'TODOS') or categoria = p_categoria;

    update productos
    set precio_unitario = precio_unitario * (1 + p_porcentaje / 100.0),
        fecha_actualizacion = now()
    where p_categoria is null or p_categoria in ('TODAS', 'TODOS') or categoria = p_categoria;

    get diagnostics v_count = row_count;
    return v_count;
end;
$$;

-- ---------- Agregaciones en el servidor ----------
-- Usadas por Dashboard, Facturación mensual y Más vendidos.
-- Todas excluyen los remitos anulados.

create or replace function facturacion_mensual()
returns table (anio integer, mes integer, cantidad bigint, total numeric)
language sql
stable
as $$
    select extract(year from fecha)::integer,
           extract(month from fecha)::integer,
           count(*),
           coalesce(sum(total), 0)
    from remitos
    where coalesce(estado, '') <> 'Anulado'
    group by 1, 2
    order by 1, 2;
$$;

create or replace function ranking_productos(p_desde date, p_limite integer, p_orden text default 'cantidad')
returns table (codigo text, descripcion text, categoria text, cantidad bigint, facturado numeric)
language sql
stable
as $$
    select coalesce(ri.codigo, '—'),
           ri.descripcion,
           coalesce(p.categoria, 'SIN CATEGORÍA'),
           sum(ri.cantidad)::bigint,
           coalesce(sum(ri.subtotal), 0)
    from remito_items ri
    join remitos r on r.id = ri.remito_id
    left join productos p on p.codigo = ri.codigo
    where coalesce(r.estado, '') <> 'Anulado'
      and (p_desde is null or r.fecha >= p_desde)
    group by 1, 2, 3
    order by case when p_orden = 'facturado' then coalesce(sum(ri.subtotal), 0)
                  else sum(ri.cantidad)::numeric end desc
    limit p_limite;
$$;

create or replace function resumen_ventas(p_desde date)
returns table (unidades bigint, productos_distintos bigint, facturado numeric)
language sql
stable
as $$
    select coalesce(sum(ri.cantidad), 0)::bigint,
           count(distinct coalesce(ri.codigo, '') || '|' || ri.descripcion),
           coalesce(sum(ri.subtotal), 0)
    from remito_items ri
    join remitos r on r.id = ri.remito_id
    where coalesce(r.estado, '') <> 'Anulado'
      and (p_desde is null or r.fecha >= p_desde);
$$;

create or replace function productos_reposicion()
returns table (codigo text, descripcion text, stock integer, stock_minimo integer)
language sql
stable
as $$
    select codigo, descripcion, stock, stock_minimo
    from productos
    where stock <= 0 or (stock_minimo > 0 and stock <= stock_minimo)
    order by stock;
$$;


-- ---------- Login por nombre de usuario ----------
-- Mapea username → email de auth.users. La tabla NO es legible con la
-- anon key: el lookup del login pasa por la función security definer.
create table if not exists user_profiles (
    id         uuid primary key references auth.users on delete cascade,
    username   text unique not null,
    email      text not null,
    created_at timestamptz default now()
);

alter table user_profiles enable row level security;

drop policy if exists "solo_propio_perfil" on user_profiles;
create policy "solo_propio_perfil" on user_profiles
    for all using (auth.uid() = id);

create or replace function login_email(p_username text)
returns text
language sql
security definer
set search_path = public
stable
as $$
    select email from user_profiles where username = lower(trim(p_username));
$$;

revoke all on function login_email(text) from public;
grant execute on function login_email(text) to anon, authenticated;

-- Para agregar un usuario:
--   1. Supabase → Authentication → Users → Add user (email + contraseña,
--      con "Auto Confirm User").
--   2. Copiar el UUID del usuario creado y ejecutar:
--      insert into user_profiles (id, username, email)
--      values ('<UUID>', 'nombredeusuario', 'email@ejemplo.com');
--      (el username en minúsculas)
